# Problem 1

In [1]:

# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin

matris = np.random.randint(0, 11, size=(5, 5))

print("Üretilen Matris:")
print(matris)

# 3 - matris'in boyutunu öğrenin


matris = np.random.randint(0, 11, size=(5, 5))

boyut = matris.shape

print("Matrisin Boyutu:", boyut)


# 4 - matris'i yeniden boyutlandırın

matris = np.random.randint(0, 11, size=(5, 5))

print("Öncelikle Oluşturulan Matris:")
print(matris)

yeniden_boyutlandirilmis_matris = np.reshape(matris, (25,))

print("Yeniden Boyutlandırılan Matris:")
print(yeniden_boyutlandirilmis_matris)


# 5 - matris'in boyut sayısını öğrenin

matris = np.random.randint(0, 11, size=(5, 5))

boyut_sayisi = matris.ndim

print("Matrisin Boyut Sayısı:", boyut_sayisi)


Üretilen Matris:
[[ 9  1  4  9  0]
 [ 6  2  6 10  6]
 [ 5  0 10  7  9]
 [ 7  5 10  7  6]
 [ 4  3  1  8  4]]
Matrisin Boyutu: (5, 5)
Öncelikle Oluşturulan Matris:
[[ 4 10  2  8  6]
 [ 9 10  2  7  1]
 [ 1  6  0 10  3]
 [ 8  8  6  5  8]
 [ 4  4  3  9  3]]
Yeniden Boyutlandırılan Matris:
[ 4 10  2  8  6  9 10  2  7  1  1  6  0 10  3  8  8  6  5  8  4  4  3  9
  3]
Matrisin Boyut Sayısı: 2


# Problem 2

In [5]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin

import numpy as np

matris = np.random.randint(1, 11, size=(3, 3)) * 2 - 1

print("Oluşturulan Matris:")
print(matris)

# 2 - Oluşturduğunuz matrisi parçalayın

parca1 = matris[:2, :2]
parca2 = matris[1:, 1:]

print(">>>> Matrisi iki parçaya ayırma <<<<")

print("Parça 1:")
print(parca1)
print("Parça 2:")
print(parca2)

# 3 - Parçalanmış matrisleri birleştirin

birlesik_matris = np.concatenate((parca1, parca2), axis=1)

print(">>>> Parçalanmış matrisleri birleştirme <<<<")
print("Birleştirilen Matris:")
print(birlesik_matris)



Oluşturulan Matris:
[[15  7 15]
 [ 9  9  7]
 [19 15  3]]
>>>> Matrisi iki parçaya ayırma <<<<
Parça 1:
[[15  7]
 [ 9  9]]
Parça 2:
[[ 9  7]
 [15  3]]
>>>> Parçalanmış matrisleri birleştirme <<<<
Birleştirilen Matris:
[[15  7  9  7]
 [ 9  9 15  3]]


# Problem 3

In [7]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin

matris = np.arange(1, 100, 2)[:10]
np.random.shuffle(matris)
matris = matris.reshape(5, 2)

# 2 - matris'in özelliklerini inceleyin

boyut = matris.shape
minimum = np.min(matris)
maksimum = np.max(matris)
toplam_eleman_sayisi = np.size(matris)
ortalama = np.mean(matris)
standart_sapma = np.std(matris)
medyan = np.median(matris)
mod = None if len(np.unique(matris)) == len(matris.flatten()) else "Yok"
toplam = np.sum(matris)

print("Matris:\n", matris)
print("Boyut (shape):", boyut)
print("Minimum değer:", minimum)
print("Maksimum değer:", maksimum)
print("Toplam eleman sayısı:", toplam_eleman_sayisi)
print("Ortalama değer:", ortalama)
print("Standart sapma:", standart_sapma)
print("Medyan:", medyan)
print("Mod:", mod)
print("Değerlerin toplamı:", toplam)


Matris:
 [[ 5  7]
 [11  3]
 [13 15]
 [19  9]
 [ 1 17]]
Boyut (shape): (5, 2)
Minimum değer: 1
Maksimum değer: 19
Toplam eleman sayısı: 10
Ortalama değer: 10.0
Standart sapma: 5.744562646538029
Medyan: 10.0
Mod: None
Değerlerin toplamı: 100
