# Problem 1 

In [155]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun

arr = np.array([3, 1, 5, 2, 4])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.

arr_sorted = np.sort(arr)

print(arr_sorted)


[1 2 3 4 5]


# Problem 2

In [156]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.

import numpy as np
arr1 = np.array([10, 15, 30, 45, 60])
print(arr1)

[10 15 30 45 60]


In [157]:
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.

arr2 = np.arange(5,16)
print(arr2)

[ 5  6  7  8  9 10 11 12 13 14 15]


In [158]:
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

arr3 = np.arange(50,101,5)
print(arr3)

[ 50  55  60  65  70  75  80  85  90  95 100]


In [159]:
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

arr4 = np.zeros(10)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [160]:
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.

arr5 = np.ones(10)
print(arr5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [161]:
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.

arr6 = np.linspace(0, 100, 5)
print(arr6)

[  0.  25.  50.  75. 100.]


In [162]:
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.

arr7 = np.random.randint(10, 31, 5)
print(arr7)

[25 18 12 11 15]


In [163]:
# 8- [-1 ile 1] arasında 10 adet sayı üretin.

arr8 = np.random.uniform(-1, 1, 10)
print(arr8)

[-0.6639429   0.6582073  -0.31418316 -0.45846639 -0.16556952  0.01637516
 -0.15558483 -0.72639607 -0.34126748 -0.4110615 ]


In [164]:
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

arr9 = np.random.randint(10, 51, (3,5))
print(arr9)

[[31 22 41 45 13]
 [48 20 32 49 26]
 [40 47 23 37 13]]


In [165]:
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

row_sum = np.sum(arr9, axis=1)
col_sum = np.sum(arr9, axis=0)
print("Satır toplamları:", row_sum)
print("Sütun toplamları:", col_sum)

Satır toplamları: [152 175 160]
Sütun toplamları: [119  89  96 131  52]


In [166]:
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

max_val = np.max(arr9)
min_val = np.min(arr9)
mean_val = np.mean(arr9)
print("En büyük değer:", max_val)
print("En küçük değer:", min_val)
print("Ortalama değer:", mean_val)


En büyük değer: 49
En küçük değer: 13
Ortalama değer: 32.46666666666667


In [167]:
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?

max_idx = np.argmax(arr9)
print("En büyük değerin indeksi:", max_idx)

En büyük değerin indeksi: 8


In [168]:
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.

arr13 = np.arange(10, 21)
print(arr13[:3])

[10 11 12]


In [169]:
# 14- Üretilen dizinin elemanlarını tersten yazdırın.

print(arr9[::-1])


[[40 47 23 37 13]
 [48 20 32 49 26]
 [31 22 41 45 13]]


In [170]:
# 15- Üretilen matrisin ilk satırını seçiniz.

first_row = arr9[0]
print(first_row)

[31 22 41 45 13]


In [171]:
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

element = arr9[1,2]
print(element)

32


In [172]:
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

first_elements = arr9[:,0]
print(first_elements)

[31 48 40]


In [173]:
# 18- Üretilen matrisin her bir elemanının karesini alınız.

squared_arr = np.square(arr9)
print(squared_arr)

[[ 961  484 1681 2025  169]
 [2304  400 1024 2401  676]
 [1600 2209  529 1369  169]]


In [174]:

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

positive_even = arr9[(arr9 > 0) & (arr9 % 2 == 0)]
print(positive_even)


[22 48 20 32 26 40]
